Bug #1066878 modules: wcn: fix -Wheader-guard warnings for clang
[root cause  ] clang build [-Werror,-Wheader-guard]
[changes     ] use right header name macro
[side effects] No
[self test   ]: Yes
[download normally]: Yes
[power on/off normally]: Yes
[do common repository/branch inspection]: Yes
[is there dependence]: No
[confirm dependent commit]: No
[board]: sp9863a
[test case]: build by clang
[reviewers   ] nianfu.bai
[change_type ] feature
[tag_product ] common

wcn/bluetooth/driver/tty-sipc/rfkill.h:19:9: error:
'__MARLIN_RFKILL_H__' is used as a header
guard here, followed by #define of a different macro
[-Werror,-Wheader-guard]
\#ifndef __MARLIN_RFKILL_H__
^~~~~~~~~~~~~~~~~~~
wcn/bluetooth/driver/tty-sipc/rfkill.h:20:9: note: '__MARLIN_RFILL_H__'
is defined here; did
you mean '__MARLIN_RFKILL_H__'?
\#define __MARLIN_RFILL_H__
^~~~~~~~~~~~~~~~~~
__MARLIN_RFKILL_H__

Change-Id: I27d422b4761abc2fdd2cdeab598960105f3acb74
Signed-off-by: Candle Sun <candle.sun@unisoc.com>