Bug #1066878 modules: wcn: fix -Wtypedef-redefinition warnings for clang
[root cause  ] clang build [-Werror,-Wtypedef-redefinition]
[changes     ] remove unused header include
[side effects] No
[self test   ]: Yes
[download normally]: Yes
[power on/off normally]: Yes
[do common repository/branch inspection]: Yes
[is there dependence]: No
[confirm dependent commit]: No
[board]: sp9863a
[test case]: build by clang
[reviewers   ] nianfu.bai
[change_type ] feature
[tag_product ] common

In file included from wcn/fm/driver/fm_sipc/fmdrv_main.c:58:
kernel4.14/include/linux/wcn_integrate_platform.h:135:15: error:
redefinition of typedef
'marlin_reset_callback' is a C11 feature
[-Werror,-Wtypedef-redefinition]
typedef int (*marlin_reset_callback) (void *para);
^
kernel4.14/include/misc/marlin_platform.h:27:15: note: previous
definition is here
typedef int (*marlin_reset_callback) (void *para);
^
In file included from wcn/fm/driver/fm_sipc/fmdrv_ops.c:53:
kernel4.14/include/linux/wcn_integrate_platform.h:135:15: error:
redefinition of typedef
'marlin_reset_callback' is a C11 feature
[-Werror,-Wtypedef-redefinition]
typedef int (*marlin_reset_callback) (void *para);
^
kernel4.14/include/misc/marlin_platform.h:27:15: note: previous
definition is here
typedef int (*marlin_reset_callback) (void *para);
^

Change-Id: I553c692ef234746f9ae0d45a986286a8bbfd7146
Signed-off-by: Candle Sun <candle.sun@unisoc.com>